# Site settings
title: Desafiios
description: "Clínica de Desenvolvimento, Saúde e Formação"
baseurl: "https://desafiios.com" # the subpath of your site, e.g. /blog
url: "https://desafiios.com" # the name of your domain
logo_url: img/logo.jpg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Clínica de Desenvolvimento, Saúde e Formação
    hero_description: 

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 224 946 762 
    mobile1: 966 613 094
    mobile2: 916 473 850
    emergency: 999 999 999
    email: geral@desafiios.com
    address: Rua da Rasa 143, Vila Nova de Gaia, Portugal

# Opening hours
monday_friday: 9:00 – 13:00 | 14:00 - 19:00
saturday: 10:00 – 13:00
sunday: Fechado

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Rua da Rasa 143, Vila Nova de Gaia, Portugal
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
#twitter: http://twitter.com
#instagram: http://instagram.com
#youtube: http://youtube.com
#skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2018 Desafiios - Todos os direitos reservados

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
